language: go

go:
  - 1.x

script:
  - mkdir -p build/
  - GOOS=windows GOARCH=amd64 go build -o build/easy-upload-windows.exe easy-upload.go
  - GOOS=darwin GOARCH=amd64 go build -o build/easy-upload-osx.command easy-upload.go
  - GOOS=linux GOARCH=amd64 go build -o build/easy-upload-linux easy-upload.go
  - chmod -R u+x build

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: build/*
