language: go

go:
  - 1.x

script:
  - mkdir -p build/
  - ./build.sh easy-upload.go

deploy:
  provider: releases
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true